### ISSUE TITLE
Timeline scrolling is stuttering at the end

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#134]
**Describe the bug**
Timeline scrolling is stuttering at the end of the animation. The animation start is always good but, at the end, there are always 2 or 3 freezes whatever the scroll length.

**To Reproduce**
1. Open a room
2. Paginate back to feed the screen
3. Scroll down or up
4. See the glitches

**Screenshots**
I scrolled only once here:
https://user-images.githubusercontent.com/8418515/179548284-9c8bc6c7-6504-4c0c-9471-7388a1ad6e93.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone 13

**Comment by stefanceriu** [comment]
Possibly fixed by https://github.com/vector-im/element-x-ios/pull/133

**Comment by manuroe** [comment]
I still see the issue on the Element PR build of #133:
https://user-images.githubusercontent.com/8418515/179927382-9ce3f291-a4bb-4080-89ae-51a9d479ef05.MP4

Note that it happens in this video on content already loaded and it is really random: when scrolling on the exact same content again, it does not always freeze. The main thread may be blocked elsewhere on receiving new events for example.
